name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --abbrev=0 --tags)"

      - name: Set package version
        run: echo "PACKAGE_VERSION=${{ steps.get_tag.outputs.tag }}" >> $GITHUB_ENV

      - name: Build package
        run: |
          pip install --upgrade pip
          pip install build
          python -m build

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
