name: Test Python Package

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      python-version:
        required: true
        type: string

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ inputs.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Create virtualenv
        run: |
          python -m venv .venv

      - name: Activate virtualenv unix
        if: ${{ inputs.os == 'ubuntu-latest' || inputs.os == 'macos-latest' }}
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Activate virtualenv windows
        if: ${{ inputs.os == 'windows-latest' }}
        run: |
          .\.venv\Scripts\Activate.ps1
          echo "PATH=$env:PATH" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install package
        run: |
          pip install --upgrade pip
          pip install .[dev,test,kafka,cache]

      - name: Run linting & unit tests
        run: |
          bandit -c pyproject.toml -r slipstream tests
          pydocstyle slipstream tests
          pyright slipstream tests

      - uses: nick-fields/retry@v3
        name: Run integration tests linux
        if: ${{ inputs.os == 'ubuntu-latest' }}
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: pytest tests/integration/
