name: Triggered Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  python-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10"]
    uses: ./.github/workflows/test.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
